const manifest = new URL(
  "../rust-wasm-emitter/Cargo.toml",
  import.meta.url,
).pathname;
const crate = new URL("../rust-wasm-emitter/", import.meta.url).pathname;
const source =
  `${crate}target/wasm32-unknown-unknown/release/gpupaper_rust_wasm_emitter.wasm`;
const wasmDestination = new URL(
  "../src/generated/rust_wasm_emitter.wasm",
  import.meta.url,
).pathname;
const moduleDestination = new URL(
  "../src/generated/rust_wasm_emitter_bytes.ts",
  import.meta.url,
).pathname;
const verifyOnly = Deno.args.includes("--check");

const build = await new Deno.Command("cargo", {
  args: [
    "build",
    "--manifest-path",
    manifest,
    "--target",
    "wasm32-unknown-unknown",
    "--release",
    "--locked",
  ],
  stdout: "inherit",
  stderr: "inherit",
}).output();
if (!build.success) {
  throw new Error(`Rust/Wasm emitter build exited ${build.code}`);
}

const builtBytes = await Deno.readFile(source);
if (verifyOnly) {
  const checkedInBytes = await Deno.readFile(wasmDestination);
  if (!equalBytes(builtBytes, checkedInBytes)) {
    throw new Error(
      `Rust/Wasm emitter artifact ${wasmDestination} differs from the release build; run deno task rust-wasm:build`,
    );
  }
  const expectedModule = emitterBytesModule(builtBytes);
  const checkedInModule = await Deno.readTextFile(moduleDestination);
  if (checkedInModule !== expectedModule) {
    throw new Error(
      `Rust/Wasm emitter module ${moduleDestination} differs from the release build; run deno task rust-wasm:build`,
    );
  }
} else {
  await Deno.mkdir(new URL("../src/generated/", import.meta.url), {
    recursive: true,
  });
  await Deno.writeFile(wasmDestination, builtBytes);
  await Deno.writeTextFile(moduleDestination, emitterBytesModule(builtBytes));
}
const bytes = verifyOnly ? builtBytes : await Deno.readFile(wasmDestination);
const module = await WebAssembly.compile(bytes as BufferSource);
const actualExports = WebAssembly.Module.exports(module).map((entry) =>
  entry.name
);
const requiredExports = [
  "memory",
  "abi_version",
  "input_resize",
  "prepare_plan",
  "emit_plan",
  "release_plan",
  "output_ptr",
  "output_len",
  "last_error_ptr",
  "last_error_len",
];
for (const required of requiredExports) {
  if (!actualExports.includes(required)) {
    throw new Error(
      `Rust/Wasm emitter omitted export ${JSON.stringify(required)}; found ${
        actualExports.join(", ")
      }`,
    );
  }
}
const instance = await WebAssembly.instantiate(module);
const abiVersion = (instance.exports.abi_version as () => number)() >>> 0;
if (abiVersion !== 2) {
  throw new Error(
    `Rust/Wasm emitter ABI must be 2; built artifact exports ${abiVersion}`,
  );
}
console.log(JSON.stringify({
  status: "completed",
  destination: wasmDestination,
  wasmBytes: bytes.byteLength,
  abiVersion,
  exports: actualExports,
  verified: verifyOnly,
}));

function equalBytes(left: Uint8Array, right: Uint8Array): boolean {
  return left.length === right.length &&
    left.every((byte, index) => byte === right[index]);
}

function emitterBytesModule(bytes: Uint8Array): string {
  const chunks = bytes.toBase64().match(/.{1,80}/g);
  if (chunks === null) {
    throw new Error("Rust/Wasm emitter cannot publish an empty module");
  }
  const literals = chunks.map((chunk) => `    ${JSON.stringify(chunk)},`).join(
    "\n",
  );
  return `// Generated by scripts/build_rust_wasm_emitter.ts.\nexport const rustWasmEmitterBytes = Uint8Array.fromBase64(\n  [\n${literals}\n  ].join(""),\n);\n`;
}
